chore(ci): show the error correction steps on failure of Check license file workfow

diff --git a/.github/workflows/check-license-file.yml b/.github/workflows/check-license-file.yml
--- a/.github/workflows/check-license-file.yml
+++ b/.github/workflows/check-license-file.yml
@@ -58,4 +58,7 @@ jobs:
         if: steps.check-changes.outputs.changed == 'true'
         run: |
           git add .
-          git diff --cached --exit-code
+          if ! git diff --cached --exit-code; then
+            echo '::error::If you changed dependencies, please run `make update-license-file` to update the license file.'
+            exit 1
+          fi
